# Generated by Django 3.2.7 on 2021-10-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20211005_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Version'),
        ),
    ]
